export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CHANGE_EDIT_STATE = 'CHANGE_EDIT_STATE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const FIX_SERVICE_FIELD = 'FIX_SERVICE_FIELD';
export const FILTER_SERVICE_FIELD = 'FILTER_SERVICE_FIELD';